services:
  - type: web
    name: hospital-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && python app.py
    envVars:
      - key: PGHOST
        fromDatabase:
          name: hospital-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: hospital-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: hospital-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: hospital-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: hospital-db
          property: password

databases:
  - name: hospital-db
    databaseName: hospital
    user: hospital_user
